//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GusWCF
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParametryWyszukiwania", Namespace="http://CIS/BIR/PUBL/2014/07/DataContract")]
    public partial class ParametryWyszukiwania : object
    {
        
        private string KrsField;
        
        private string KrsyField;
        
        private string NipField;
        
        private string NipyField;
        
        private string RegonField;
        
        private string Regony14znField;
        
        private string Regony9znField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Krs
        {
            get
            {
                return this.KrsField;
            }
            set
            {
                this.KrsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Krsy
        {
            get
            {
                return this.KrsyField;
            }
            set
            {
                this.KrsyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nip
        {
            get
            {
                return this.NipField;
            }
            set
            {
                this.NipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nipy
        {
            get
            {
                return this.NipyField;
            }
            set
            {
                this.NipyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Regon
        {
            get
            {
                return this.RegonField;
            }
            set
            {
                this.RegonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Regony14zn
        {
            get
            {
                return this.Regony14znField;
            }
            set
            {
                this.Regony14znField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Regony9zn
        {
            get
            {
                return this.Regony9znField;
            }
            set
            {
                this.Regony9znField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://CIS/BIR/PUBL/2014/07", ConfigurationName="GusWCF.IUslugaBIRzewnPubl")]
    public interface IUslugaBIRzewnPubl
    {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://CIS/BIR/2014/07) of message PobierzCaptchaRequest does not match the default value (http://CIS/BIR/PUBL/2014/07)
        [System.ServiceModel.OperationContractAttribute(Action="http://CIS/BIR/2014/07/IUslugaBIR/PobierzCaptcha", ReplyAction="http://CIS/BIR/2014/07/IUslugaBIR/PobierzCaptchaResponse")]
        GusWCF.PobierzCaptchaResponse PobierzCaptcha(GusWCF.PobierzCaptchaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CIS/BIR/2014/07/IUslugaBIR/PobierzCaptcha", ReplyAction="http://CIS/BIR/2014/07/IUslugaBIR/PobierzCaptchaResponse")]
        System.Threading.Tasks.Task<GusWCF.PobierzCaptchaResponse> PobierzCaptchaAsync(GusWCF.PobierzCaptchaRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://CIS/BIR/2014/07) of message SprawdzCaptchaRequest does not match the default value (http://CIS/BIR/PUBL/2014/07)
        [System.ServiceModel.OperationContractAttribute(Action="http://CIS/BIR/2014/07/IUslugaBIR/SprawdzCaptcha", ReplyAction="http://CIS/BIR/2014/07/IUslugaBIR/SprawdzCaptchaResponse")]
        GusWCF.SprawdzCaptchaResponse SprawdzCaptcha(GusWCF.SprawdzCaptchaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CIS/BIR/2014/07/IUslugaBIR/SprawdzCaptcha", ReplyAction="http://CIS/BIR/2014/07/IUslugaBIR/SprawdzCaptchaResponse")]
        System.Threading.Tasks.Task<GusWCF.SprawdzCaptchaResponse> SprawdzCaptchaAsync(GusWCF.SprawdzCaptchaRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://CIS/BIR/2014/07) of message SetValueRequest does not match the default value (http://CIS/BIR/PUBL/2014/07)
        [System.ServiceModel.OperationContractAttribute(Action="http://CIS/BIR/2014/07/IUslugaBIR/SetValue", ReplyAction="http://CIS/BIR/2014/07/IUslugaBIR/SetValueResponse")]
        GusWCF.SetValueResponse SetValue(GusWCF.SetValueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CIS/BIR/2014/07/IUslugaBIR/SetValue", ReplyAction="http://CIS/BIR/2014/07/IUslugaBIR/SetValueResponse")]
        System.Threading.Tasks.Task<GusWCF.SetValueResponse> SetValueAsync(GusWCF.SetValueRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://CIS/BIR/2014/07) of message GetValueRequest does not match the default value (http://CIS/BIR/PUBL/2014/07)
        [System.ServiceModel.OperationContractAttribute(Action="http://CIS/BIR/2014/07/IUslugaBIR/GetValue", ReplyAction="http://CIS/BIR/2014/07/IUslugaBIR/GetValueResponse")]
        GusWCF.GetValueResponse GetValue(GusWCF.GetValueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CIS/BIR/2014/07/IUslugaBIR/GetValue", ReplyAction="http://CIS/BIR/2014/07/IUslugaBIR/GetValueResponse")]
        System.Threading.Tasks.Task<GusWCF.GetValueResponse> GetValueAsync(GusWCF.GetValueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/Zaloguj", ReplyAction="http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/ZalogujResponse")]
        string Zaloguj(string pKluczUzytkownika);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/Zaloguj", ReplyAction="http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/ZalogujResponse")]
        System.Threading.Tasks.Task<string> ZalogujAsync(string pKluczUzytkownika);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/Wyloguj", ReplyAction="http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/WylogujResponse")]
        bool Wyloguj(string pIdentyfikatorSesji);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/Wyloguj", ReplyAction="http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/WylogujResponse")]
        System.Threading.Tasks.Task<bool> WylogujAsync(string pIdentyfikatorSesji);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/DaneSzukaj", ReplyAction="http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/DaneSzukajResponse")]
        string DaneSzukaj(GusWCF.ParametryWyszukiwania pParametryWyszukiwania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/DaneSzukaj", ReplyAction="http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/DaneSzukajResponse")]
        System.Threading.Tasks.Task<string> DaneSzukajAsync(GusWCF.ParametryWyszukiwania pParametryWyszukiwania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/DanePobierzPelnyRaport", ReplyAction="http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/DanePobierzPelnyRaportResponse")]
        string DanePobierzPelnyRaport(string pRegon, string pNazwaRaportu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/DanePobierzPelnyRaport", ReplyAction="http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/DanePobierzPelnyRaportResponse")]
        System.Threading.Tasks.Task<string> DanePobierzPelnyRaportAsync(string pRegon, string pNazwaRaportu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/DaneKomunikat", ReplyAction="http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/DaneKomunikatResponse")]
        string DaneKomunikat();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/DaneKomunikat", ReplyAction="http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/DaneKomunikatResponse")]
        System.Threading.Tasks.Task<string> DaneKomunikatAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PobierzCaptcha", WrapperNamespace="http://CIS/BIR/2014/07", IsWrapped=true)]
    public partial class PobierzCaptchaRequest
    {
        
        public PobierzCaptchaRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PobierzCaptchaResponse", WrapperNamespace="http://CIS/BIR/2014/07", IsWrapped=true)]
    public partial class PobierzCaptchaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CIS/BIR/2014/07", Order=0)]
        public string PobierzCaptchaResult;
        
        public PobierzCaptchaResponse()
        {
        }
        
        public PobierzCaptchaResponse(string PobierzCaptchaResult)
        {
            this.PobierzCaptchaResult = PobierzCaptchaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SprawdzCaptcha", WrapperNamespace="http://CIS/BIR/2014/07", IsWrapped=true)]
    public partial class SprawdzCaptchaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CIS/BIR/2014/07", Order=0)]
        public string pCaptcha;
        
        public SprawdzCaptchaRequest()
        {
        }
        
        public SprawdzCaptchaRequest(string pCaptcha)
        {
            this.pCaptcha = pCaptcha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SprawdzCaptchaResponse", WrapperNamespace="http://CIS/BIR/2014/07", IsWrapped=true)]
    public partial class SprawdzCaptchaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CIS/BIR/2014/07", Order=0)]
        public bool SprawdzCaptchaResult;
        
        public SprawdzCaptchaResponse()
        {
        }
        
        public SprawdzCaptchaResponse(bool SprawdzCaptchaResult)
        {
            this.SprawdzCaptchaResult = SprawdzCaptchaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetValue", WrapperNamespace="http://CIS/BIR/2014/07", IsWrapped=true)]
    public partial class SetValueRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CIS/BIR/2014/07", Order=0)]
        public string pNazwaParametru;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CIS/BIR/2014/07", Order=1)]
        public string pWartoscParametru;
        
        public SetValueRequest()
        {
        }
        
        public SetValueRequest(string pNazwaParametru, string pWartoscParametru)
        {
            this.pNazwaParametru = pNazwaParametru;
            this.pWartoscParametru = pWartoscParametru;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetValueResponse", WrapperNamespace="http://CIS/BIR/2014/07", IsWrapped=true)]
    public partial class SetValueResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CIS/BIR/2014/07", Order=0)]
        public string SetValueResult;
        
        public SetValueResponse()
        {
        }
        
        public SetValueResponse(string SetValueResult)
        {
            this.SetValueResult = SetValueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetValue", WrapperNamespace="http://CIS/BIR/2014/07", IsWrapped=true)]
    public partial class GetValueRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CIS/BIR/2014/07", Order=0)]
        public string pNazwaParametru;
        
        public GetValueRequest()
        {
        }
        
        public GetValueRequest(string pNazwaParametru)
        {
            this.pNazwaParametru = pNazwaParametru;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetValueResponse", WrapperNamespace="http://CIS/BIR/2014/07", IsWrapped=true)]
    public partial class GetValueResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CIS/BIR/2014/07", Order=0)]
        public string GetValueResult;
        
        public GetValueResponse()
        {
        }
        
        public GetValueResponse(string GetValueResult)
        {
            this.GetValueResult = GetValueResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IUslugaBIRzewnPublChannel : GusWCF.IUslugaBIRzewnPubl, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class UslugaBIRzewnPublClient : System.ServiceModel.ClientBase<GusWCF.IUslugaBIRzewnPubl>, GusWCF.IUslugaBIRzewnPubl
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public UslugaBIRzewnPublClient() : 
                base(UslugaBIRzewnPublClient.GetDefaultBinding(), UslugaBIRzewnPublClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.e3.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UslugaBIRzewnPublClient(EndpointConfiguration endpointConfiguration) : 
                base(UslugaBIRzewnPublClient.GetBindingForEndpoint(endpointConfiguration), UslugaBIRzewnPublClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UslugaBIRzewnPublClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(UslugaBIRzewnPublClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UslugaBIRzewnPublClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(UslugaBIRzewnPublClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UslugaBIRzewnPublClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GusWCF.PobierzCaptchaResponse GusWCF.IUslugaBIRzewnPubl.PobierzCaptcha(GusWCF.PobierzCaptchaRequest request)
        {
            return base.Channel.PobierzCaptcha(request);
        }
        
        public string PobierzCaptcha()
        {
            GusWCF.PobierzCaptchaRequest inValue = new GusWCF.PobierzCaptchaRequest();
            GusWCF.PobierzCaptchaResponse retVal = ((GusWCF.IUslugaBIRzewnPubl)(this)).PobierzCaptcha(inValue);
            return retVal.PobierzCaptchaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GusWCF.PobierzCaptchaResponse> GusWCF.IUslugaBIRzewnPubl.PobierzCaptchaAsync(GusWCF.PobierzCaptchaRequest request)
        {
            return base.Channel.PobierzCaptchaAsync(request);
        }
        
        public System.Threading.Tasks.Task<GusWCF.PobierzCaptchaResponse> PobierzCaptchaAsync()
        {
            GusWCF.PobierzCaptchaRequest inValue = new GusWCF.PobierzCaptchaRequest();
            return ((GusWCF.IUslugaBIRzewnPubl)(this)).PobierzCaptchaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GusWCF.SprawdzCaptchaResponse GusWCF.IUslugaBIRzewnPubl.SprawdzCaptcha(GusWCF.SprawdzCaptchaRequest request)
        {
            return base.Channel.SprawdzCaptcha(request);
        }
        
        public bool SprawdzCaptcha(string pCaptcha)
        {
            GusWCF.SprawdzCaptchaRequest inValue = new GusWCF.SprawdzCaptchaRequest();
            inValue.pCaptcha = pCaptcha;
            GusWCF.SprawdzCaptchaResponse retVal = ((GusWCF.IUslugaBIRzewnPubl)(this)).SprawdzCaptcha(inValue);
            return retVal.SprawdzCaptchaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GusWCF.SprawdzCaptchaResponse> GusWCF.IUslugaBIRzewnPubl.SprawdzCaptchaAsync(GusWCF.SprawdzCaptchaRequest request)
        {
            return base.Channel.SprawdzCaptchaAsync(request);
        }
        
        public System.Threading.Tasks.Task<GusWCF.SprawdzCaptchaResponse> SprawdzCaptchaAsync(string pCaptcha)
        {
            GusWCF.SprawdzCaptchaRequest inValue = new GusWCF.SprawdzCaptchaRequest();
            inValue.pCaptcha = pCaptcha;
            return ((GusWCF.IUslugaBIRzewnPubl)(this)).SprawdzCaptchaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GusWCF.SetValueResponse GusWCF.IUslugaBIRzewnPubl.SetValue(GusWCF.SetValueRequest request)
        {
            return base.Channel.SetValue(request);
        }
        
        public string SetValue(string pNazwaParametru, string pWartoscParametru)
        {
            GusWCF.SetValueRequest inValue = new GusWCF.SetValueRequest();
            inValue.pNazwaParametru = pNazwaParametru;
            inValue.pWartoscParametru = pWartoscParametru;
            GusWCF.SetValueResponse retVal = ((GusWCF.IUslugaBIRzewnPubl)(this)).SetValue(inValue);
            return retVal.SetValueResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GusWCF.SetValueResponse> GusWCF.IUslugaBIRzewnPubl.SetValueAsync(GusWCF.SetValueRequest request)
        {
            return base.Channel.SetValueAsync(request);
        }
        
        public System.Threading.Tasks.Task<GusWCF.SetValueResponse> SetValueAsync(string pNazwaParametru, string pWartoscParametru)
        {
            GusWCF.SetValueRequest inValue = new GusWCF.SetValueRequest();
            inValue.pNazwaParametru = pNazwaParametru;
            inValue.pWartoscParametru = pWartoscParametru;
            return ((GusWCF.IUslugaBIRzewnPubl)(this)).SetValueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GusWCF.GetValueResponse GusWCF.IUslugaBIRzewnPubl.GetValue(GusWCF.GetValueRequest request)
        {
            return base.Channel.GetValue(request);
        }
        
        public string GetValue(string pNazwaParametru)
        {
            GusWCF.GetValueRequest inValue = new GusWCF.GetValueRequest();
            inValue.pNazwaParametru = pNazwaParametru;
            GusWCF.GetValueResponse retVal = ((GusWCF.IUslugaBIRzewnPubl)(this)).GetValue(inValue);
            return retVal.GetValueResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GusWCF.GetValueResponse> GusWCF.IUslugaBIRzewnPubl.GetValueAsync(GusWCF.GetValueRequest request)
        {
            return base.Channel.GetValueAsync(request);
        }
        
        public System.Threading.Tasks.Task<GusWCF.GetValueResponse> GetValueAsync(string pNazwaParametru)
        {
            GusWCF.GetValueRequest inValue = new GusWCF.GetValueRequest();
            inValue.pNazwaParametru = pNazwaParametru;
            return ((GusWCF.IUslugaBIRzewnPubl)(this)).GetValueAsync(inValue);
        }
        
        public string Zaloguj(string pKluczUzytkownika)
        {
            return base.Channel.Zaloguj(pKluczUzytkownika);
        }
        
        public System.Threading.Tasks.Task<string> ZalogujAsync(string pKluczUzytkownika)
        {
            return base.Channel.ZalogujAsync(pKluczUzytkownika);
        }
        
        public bool Wyloguj(string pIdentyfikatorSesji)
        {
            return base.Channel.Wyloguj(pIdentyfikatorSesji);
        }
        
        public System.Threading.Tasks.Task<bool> WylogujAsync(string pIdentyfikatorSesji)
        {
            return base.Channel.WylogujAsync(pIdentyfikatorSesji);
        }
        
        public string DaneSzukaj(GusWCF.ParametryWyszukiwania pParametryWyszukiwania)
        {
            return base.Channel.DaneSzukaj(pParametryWyszukiwania);
        }
        
        public System.Threading.Tasks.Task<string> DaneSzukajAsync(GusWCF.ParametryWyszukiwania pParametryWyszukiwania)
        {
            return base.Channel.DaneSzukajAsync(pParametryWyszukiwania);
        }
        
        public string DanePobierzPelnyRaport(string pRegon, string pNazwaRaportu)
        {
            return base.Channel.DanePobierzPelnyRaport(pRegon, pNazwaRaportu);
        }
        
        public System.Threading.Tasks.Task<string> DanePobierzPelnyRaportAsync(string pRegon, string pNazwaRaportu)
        {
            return base.Channel.DanePobierzPelnyRaportAsync(pRegon, pNazwaRaportu);
        }
        
        public string DaneKomunikat()
        {
            return base.Channel.DaneKomunikat();
        }
        
        public System.Threading.Tasks.Task<string> DaneKomunikatAsync()
        {
            return base.Channel.DaneKomunikatAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.e3))
            {
                System.ServiceModel.WSHttpBinding result = new System.ServiceModel.WSHttpBinding();
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.SecurityMode.Transport;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.None;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.e3))
            {
                return new System.ServiceModel.EndpointAddress("https://wyszukiwarkaregontest.stat.gov.pl/wsBIR/UslugaBIRzewnPubl.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return UslugaBIRzewnPublClient.GetBindingForEndpoint(EndpointConfiguration.e3);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return UslugaBIRzewnPublClient.GetEndpointAddress(EndpointConfiguration.e3);
        }
        
        public enum EndpointConfiguration
        {
            
            e3,
        }
    }
}
